#!/bin/bash

TOOLS_IMAGE="opencanarias/taple-tools:0.1"

while getopts "hV" opt; do
  case ${opt} in
    h )
      h=true
      ;;
    V )
      V=true
      ;;
    \? )
      echo "Invalid Option: $OPTARG" 1>&2
      exit 1
      ;;
  esac
done

if [ $h ]; then
  set -h
fi

if [ $V ]; then
  set -V
fi

docker run -e TOOL=sign -e SIGN_PRIVATE_KEY=$1 -e SIGN_PAYLOAD="$2" $TOOLS_IMAGE